# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-14 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonghu', '0002_auto_20190106_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='yhb',
            name='e_active',
            field=models.BooleanField(default=False, verbose_name='邮件是否激活'),
        ),
    ]
